# Generated by Django 2.2.3 on 2020-04-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNUmato', '0002_auto_20200501_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_order',
            name='u_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='u_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
