# Generated by Django 2.2.3 on 2020-05-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNUmato', '0007_auto_20200502_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
