# Generated by Django 2.2.3 on 2020-04-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNUmato', '0002_current_order_menu_item_orders_restaurant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='current_order',
            table='Current_order',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='Orders',
        ),
    ]
