# Generated by Django 2.2.3 on 2020-04-26 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SNUmato', '0003_auto_20200426_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_order',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='item_cost',
            field=models.PositiveIntegerField(),
        ),
    ]
