# Generated by Django 2.2.3 on 2020-05-02 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SNUmato', '0004_auto_20200502_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
