# Generated by Django 2.2.3 on 2020-05-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNUmato', '0005_auto_20200502_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
