# Generated by Django 2.2.3 on 2020-05-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNUmato', '0008_auto_20200504_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_order',
            name='u_id',
        ),
    ]
