# Generated by Django 2.2.3 on 2020-05-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNUmato', '0009_remove_current_order_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
